### ISSUE TITLE
@include background-image() includes background image twice

### ISSUE THREAD

**Issue by pdehaan** [lacroixdesign/node-bourbon#25]
I'm trying to use `@include background-image(url('/images/bar.png'));` and noticing that the `background-image` declaration is duplicated in my generated CSS file.

```sh
$ npm ls --depth 0
bourbon-test@1.0.0 /Users/pdehaan/dev/tmp/del/bourbon-test
├── gulp@3.9.0
├── gulp-sass@2.0.4
└── node-bourbon@4.2.3
```

---

### gulpfile.js:
```js
var bourbonIncludePaths = require('node-bourbon').includePaths;
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('sass', function () {
  gulp.src('./main.scss')
    .pipe(sass({
      includePaths: [bourbonIncludePaths]
    }))
    .pipe(gulp.dest('out/'));
});
```

### ./main.scss:
```scss
@import 'bourbon';

.foo {
  @include background-image(url('/images/bar.png'));
}
```

### ./out/main.css (generated via `$ gulp sass`):
```css
.foo {
  background-image: url("/images/bar.png");
  background-image: url("/images/bar.png"); }
```

**Comment by pjmay** [comment]
I can confirm this

**Comment by iamlacroix** [comment]
The `background-image` mixin is for working with multiple background images & gradients. It outputs both WebKit-compatible and spec-compliant properties. Since gradients aren't being used in the above examples, there won't be any difference between the two outputs.

Given the examples, wouldn't the Bourbon mixin be overkill in this situation? Using standard CSS would be simpler & equally as effective:

```scss
// Use this, just CSS:
.foo {
  background-image: url('/images/bar.png');
}

// Unnecessary in this situation:
.foo {
  @include background-image(url('/images/bar.png'));
}
```

The `background-image` documentation can be found here: [http://bourbon.io/docs/#background-image](http://bourbon.io/docs/#background-image)

Hope that helps!
